/* Requires the Docker Pipeline plugin */
pipeline {
    agent { docker { image 'denoland/deno:1.10.3' } }
    stages {
        stage('build') {
            steps {
                sh 'echo "[valle] Running Jenkins build"'
                sh 'deno --version'
            }
        }
    }
}